name:    projeto
version: "0.0.0"

dependencies:
- base
- yesod
- yesod-core
- yesod-static
- text
- persistent
- persistent-postgresql
- monad-logger

# The library contains all of our application code. The executable
# defined below is just a thin wrapper.
library:
  source-dirs: src

# Runnable executable for our application
executables:
  projeto:
    main: Main.hs
    source-dirs: src
    other-modules:  Foundation
                    Application
                    Home
                    Handler.Estoqueporcelana
                    Handler.Estoquemoldura
                    Handler.Falecom
                    Handler.Usr
                    Handler.Orcporcelana
                    Handler.Orcmoldura
                    Handler.Pedidomoldura
                    Handler.Pedidoporcelana
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - projeto
